package org.example;

public enum RelationType {
    FATHER, MOTHER, BROTHER, SISTER, SON, COUSIN, GRANDMOTHER, GRANDFATHER, EXHUSBANT, EXWIFE, GRANDSON, SONINLAW, GRANDDAUGHTER, SISTERINLAW, AUNT, UNCLE, HUSBAND, WIFE, NEPHEW, DAUGHTER, MOTHERINLAW, BROTHERINLAW, DAUGHTERINLAW, SISTERINLOW, EXHUSBENT, NIECE
}
